-------------------------------
--  province
-------------------------------
-- SELECT setval('province_id_seq', 71, true);

insert into province (id, abbreviation, name) values (1, 'Other', 'Other');
insert into province (id, abbreviation, name) values (2, 'AK', 'Alaska');
insert into province (id, abbreviation, name) values (3, 'AL', 'Alabama');
insert into province (id, abbreviation, name) values (4, 'AR', 'Arkansas');
insert into province (id, abbreviation, name) values (5, 'AS', 'American Samoa');
insert into province (id, abbreviation, name) values (6, 'AZ', 'Arizona');
insert into province (id, abbreviation, name) values (7, 'CA', 'California');
insert into province (id, abbreviation, name) values (8, 'CO', 'Colorado');
insert into province (id, abbreviation, name) values (9, 'CT', 'Connecticut');
insert into province (id, abbreviation, name) values (10, 'DC', 'District of Columbia');
insert into province (id, abbreviation, name) values (11, 'DE', 'Delaware');
insert into province (id, abbreviation, name) values (12, 'FL', 'Florida');
insert into province (id, abbreviation, name) values (13, 'FM', 'Federated provinces of Micronesia');
insert into province (id, abbreviation, name) values (14, 'GA', 'Georgia');
insert into province (id, abbreviation, name) values (15, 'GU', 'Guam');
insert into province (id, abbreviation, name) values (16, 'HI', 'Hawaii');
insert into province (id, abbreviation, name) values (17, 'IA', 'Iowa');
insert into province (id, abbreviation, name) values (18, 'ID', 'Idaho');
insert into province (id, abbreviation, name) values (19, 'IL', 'Illinois');
insert into province (id, abbreviation, name) values (20, 'IN', 'Indiana');
insert into province (id, abbreviation, name) values (21, 'KS', 'Kansas');
insert into province (id, abbreviation, name) values (22, 'KY', 'Kentucky');
insert into province (id, abbreviation, name) values (23, 'LA', 'Louisiana');
insert into province (id, abbreviation, name) values (24, 'MA', 'Massachusetts');
insert into province (id, abbreviation, name) values (25, 'ME', 'Maine');
insert into province (id, abbreviation, name) values (26, 'MD', 'Maryland');
insert into province (id, abbreviation, name) values (27, 'MH', 'Marshall Islands');
insert into province (id, abbreviation, name) values (28, 'MI', 'Michigan');
insert into province (id, abbreviation, name) values (29, 'MN', 'Minnesota');
insert into province (id, abbreviation, name) values (30, 'MO', 'Missouri');
insert into province (id, abbreviation, name) values (31, 'MP', 'Northern Mariana Islands');
insert into province (id, abbreviation, name) values (32, 'MS', 'Mississippi');
insert into province (id, abbreviation, name) values (33, 'MT', 'Montana');
insert into province (id, abbreviation, name) values (34, 'NC', 'North Carolina');
insert into province (id, abbreviation, name) values (35, 'ND', 'North Dakota');
insert into province (id, abbreviation, name) values (36, 'NE', 'Nebraska');
insert into province (id, abbreviation, name) values (37, 'NH', 'New Hampshire');
insert into province (id, abbreviation, name) values (38, 'NJ', 'New Jersey');
insert into province (id, abbreviation, name) values (39, 'NM', 'New Mexico');
insert into province (id, abbreviation, name) values (40, 'NV', 'Nevada');
insert into province (id, abbreviation, name) values (41, 'NY', 'New York');
insert into province (id, abbreviation, name) values (42, 'OH', 'Ohio');
insert into province (id, abbreviation, name) values (43, 'OK', 'Oklahoma');
insert into province (id, abbreviation, name) values (44, 'OR', 'Oregon');
insert into province (id, abbreviation, name) values (45, 'PA', 'Pennsylvania');
insert into province (id, abbreviation, name) values (46, 'PR', 'Puerto Rico');
insert into province (id, abbreviation, name) values (47, 'PW', 'Palau');
insert into province (id, abbreviation, name) values (48, 'RI', 'Rhode Island');
insert into province (id, abbreviation, name) values (49, 'SC', 'South Carolina');
insert into province (id, abbreviation, name) values (50, 'SD', 'South Dakota');
insert into province (id, abbreviation, name) values (51, 'TN', 'Tennessee');
insert into province (id, abbreviation, name) values (52, 'TX', 'Texas');
insert into province (id, abbreviation, name) values (53, 'UT', 'Utah');
insert into province (id, abbreviation, name) values (54, 'VI', 'Virgin Islands');
insert into province (id, abbreviation, name) values (55, 'VT', 'Vermont');
insert into province (id, abbreviation, name) values (56, 'VA', 'Virginia');
insert into province (id, abbreviation, name) values (57, 'WA', 'Washington');
insert into province (id, abbreviation, name) values (58, 'WI', 'Wisconsin');
insert into province (id, abbreviation, name) values (59, 'WV', 'West Virginia');
insert into province (id, abbreviation, name) values (60, 'WY', 'Wyoming');
-- Canada
insert into province (id, abbreviation, name) values (61, 'ON', 'Ontario');
insert into province (id, abbreviation, name) values (62, 'QC', 'Quebec');
insert into province (id, abbreviation, name) values (63, 'NS', 'Nova Scotia');
insert into province (id, abbreviation, name) values (64, 'NB', 'New Brunswick');
insert into province (id, abbreviation, name) values (65, 'MB', 'Manitoba');
insert into province (id, abbreviation, name) values (66, 'BC', 'British Columbia');
insert into province (id, abbreviation, name) values (67, 'PE', 'Prince Edward Island');
insert into province (id, abbreviation, name) values (68, 'SK', 'Saskatchewan');
insert into province (id, abbreviation, name) values (69, 'AB', 'Alberta');
insert into province (id, abbreviation, name) values (70, 'NL', 'Newfoundland and Labrador');


-------------------------------
--  country
-------------------------------
-- SELECT setval('country_id_seq', 246, true);

insert into country (id, name, two_digit_code) values (1, 'United States of America', 'US');
insert into country (id, name, two_digit_code) values (2, 'Andorra', 'AD');
insert into country (id, name, two_digit_code) values (3, 'United Arab Emirates', 'AE');
insert into country (id, name, two_digit_code) values (4, 'Afghanistan', 'AF');
insert into country (id, name, two_digit_code) values (5, 'Antigua and Barbuda', 'AG');
insert into country (id, name, two_digit_code) values (6, 'Anguilla', 'AI');
insert into country (id, name, two_digit_code) values (7, 'Albania', 'AL');
insert into country (id, name, two_digit_code) values (8, 'Armenia', 'AM');
insert into country (id, name, two_digit_code) values (9, 'Netherlands Antilles', 'AN');
insert into country (id, name, two_digit_code) values (10, 'Angola', 'AO');
insert into country (id, name, two_digit_code) values (11, 'Antarctica', 'AQ');
insert into country (id, name, two_digit_code) values (12, 'Argentina', 'AR');
insert into country (id, name, two_digit_code) values (13, 'American Samoa', 'AS');
insert into country (id, name, two_digit_code) values (14, 'Austria', 'AT');
insert into country (id, name, two_digit_code) values (15, 'Australia', 'AU');
insert into country (id, name, two_digit_code) values (16, 'Aruba', 'AW');
insert into country (id, name, two_digit_code) values (17, 'Åland Islands', 'AX');
insert into country (id, name, two_digit_code) values (18, 'Azerbaijan', 'AZ');
insert into country (id, name, two_digit_code) values (19, 'Bosnia and Herzegovina', 'BA');
insert into country (id, name, two_digit_code) values (20, 'Barbados', 'BB');
insert into country (id, name, two_digit_code) values (21, 'Bangladesh', 'BD');
insert into country (id, name, two_digit_code) values (22, 'Belgium', 'BE');
insert into country (id, name, two_digit_code) values (23, 'Burkina Faso', 'BF');
insert into country (id, name, two_digit_code) values (24, 'Bulgaria', 'BG');
insert into country (id, name, two_digit_code) values (25, 'Bahrain', 'BH');
insert into country (id, name, two_digit_code) values (26, 'Burundi', 'BI');
insert into country (id, name, two_digit_code) values (27, 'Benin', 'BJ');
insert into country (id, name, two_digit_code) values (28, 'Saint Barthélemy', 'BL');
insert into country (id, name, two_digit_code) values (29, 'Bermuda', 'BM');
insert into country (id, name, two_digit_code) values (30, 'Brunei Darussalam', 'BN');
insert into country (id, name, two_digit_code) values (31, 'Bolivia', 'BO');
insert into country (id, name, two_digit_code) values (32, 'Brazil', 'BR');
insert into country (id, name, two_digit_code) values (33, 'Bahamas', 'BS');
insert into country (id, name, two_digit_code) values (34, 'Bhutan', 'BT');
insert into country (id, name, two_digit_code) values (35, 'Bouvet Island', 'BV');
insert into country (id, name, two_digit_code) values (36, 'Botswana', 'BW');
insert into country (id, name, two_digit_code) values (37, 'Belarus', 'BY');
insert into country (id, name, two_digit_code) values (38, 'Belize', 'BZ');
insert into country (id, name, two_digit_code) values (39, 'Canada', 'CA');
insert into country (id, name, two_digit_code) values (40, 'Cocos (Keeling) Islands', 'CC');
insert into country (id, name, two_digit_code) values (41, 'Congo, the Democratic Republic of the', 'CD');
insert into country (id, name, two_digit_code) values (42, 'Central African Republic', 'CF');
insert into country (id, name, two_digit_code) values (43, 'Congo', 'CG');
insert into country (id, name, two_digit_code) values (44, 'Switzerland', 'CH');
insert into country (id, name, two_digit_code) values (45, 'Côte d''Ivoire', 'CI');
insert into country (id, name, two_digit_code) values (46, 'Cook Islands', 'CK');
insert into country (id, name, two_digit_code) values (47, 'Chile', 'CL');
insert into country (id, name, two_digit_code) values (48, 'Cameroon', 'CM');
insert into country (id, name, two_digit_code) values (49, 'China', 'CN');
insert into country (id, name, two_digit_code) values (50, 'Colombia', 'CO');
insert into country (id, name, two_digit_code) values (51, 'Costa Rica', 'CR');
insert into country (id, name, two_digit_code) values (52, 'Cuba', 'CU');
insert into country (id, name, two_digit_code) values (53, 'Cape Verde', 'CV');
insert into country (id, name, two_digit_code) values (54, 'Christmas Island', 'CX');
insert into country (id, name, two_digit_code) values (55, 'Cyprus', 'CY');
insert into country (id, name, two_digit_code) values (56, 'Czech Republic', 'CZ');
insert into country (id, name, two_digit_code) values (57, 'Germany', 'DE');
insert into country (id, name, two_digit_code) values (58, 'Djibouti', 'DJ');
insert into country (id, name, two_digit_code) values (59, 'Denmark', 'DK');
insert into country (id, name, two_digit_code) values (60, 'Dominica', 'DM');
insert into country (id, name, two_digit_code) values (61, 'Dominican Republic', 'DO');
insert into country (id, name, two_digit_code) values (62, 'Algeria', 'DZ');
insert into country (id, name, two_digit_code) values (63, 'Ecuador', 'EC');
insert into country (id, name, two_digit_code) values (64, 'Estonia', 'EE');
insert into country (id, name, two_digit_code) values (65, 'Egypt', 'EG');
insert into country (id, name, two_digit_code) values (66, 'Western Sahara', 'EH');
insert into country (id, name, two_digit_code) values (67, 'Eritrea', 'ER');
insert into country (id, name, two_digit_code) values (68, 'Spain', 'ES');
insert into country (id, name, two_digit_code) values (69, 'Ethiopia', 'ET');
insert into country (id, name, two_digit_code) values (70, 'Finland', 'FI');
insert into country (id, name, two_digit_code) values (71, 'Fiji', 'FJ');
insert into country (id, name, two_digit_code) values (72, 'Falkland Islands (Malvinas)', 'FK');
insert into country (id, name, two_digit_code) values (73, 'Micronesia, Federated State of', 'FM');
insert into country (id, name, two_digit_code) values (74, 'Faroe Islands', 'FO');
insert into country (id, name, two_digit_code) values (75, 'France', 'FR');
insert into country (id, name, two_digit_code) values (76, 'Gabon', 'GA');
insert into country (id, name, two_digit_code) values (77, 'United Kingdom', 'GB');
insert into country (id, name, two_digit_code) values (78, 'Grenada', 'GD');
insert into country (id, name, two_digit_code) values (79, 'Georgia', 'GE');
insert into country (id, name, two_digit_code) values (80, 'French Guiana', 'GF');
insert into country (id, name, two_digit_code) values (81, 'Guernsey', 'GG');
insert into country (id, name, two_digit_code) values (82, 'Ghana', 'GH');
insert into country (id, name, two_digit_code) values (83, 'Gibraltar', 'GI');
insert into country (id, name, two_digit_code) values (84, 'Greenland', 'GL');
insert into country (id, name, two_digit_code) values (85, 'Gambia', 'GM');
insert into country (id, name, two_digit_code) values (86, 'Guinea', 'GN');
insert into country (id, name, two_digit_code) values (87, 'Guadeloupe', 'GP');
insert into country (id, name, two_digit_code) values (88, 'Equatorial Guinea', 'GQ');
insert into country (id, name, two_digit_code) values (89, 'Greece', 'GR');
insert into country (id, name, two_digit_code) values (90, 'South Georgia and the South Sandwich Islands', 'GS');
insert into country (id, name, two_digit_code) values (91, 'Guatemala', 'GT');
insert into country (id, name, two_digit_code) values (92, 'Guam', 'GU');
insert into country (id, name, two_digit_code) values (93, 'Guinea-Bissau', 'GW');
insert into country (id, name, two_digit_code) values (94, 'Guyana', 'GY');
insert into country (id, name, two_digit_code) values (95, 'Hong Kong', 'HK');
insert into country (id, name, two_digit_code) values (96, 'Heard Island and McDonald Islands', 'HM');
insert into country (id, name, two_digit_code) values (97, 'Honduras', 'HN');
insert into country (id, name, two_digit_code) values (98, 'Croatia', 'HR');
insert into country (id, name, two_digit_code) values (99, 'Haiti', 'HT');
insert into country (id, name, two_digit_code) values (100, 'Hungary', 'HU');
insert into country (id, name, two_digit_code) values (101, 'Indonesia', 'ID');
insert into country (id, name, two_digit_code) values (102, 'Ireland', 'IE');
insert into country (id, name, two_digit_code) values (103, 'Israel', 'IL');
insert into country (id, name, two_digit_code) values (104, 'Isle of Man', 'IM');
insert into country (id, name, two_digit_code) values (105, 'India', 'IN');
insert into country (id, name, two_digit_code) values (106, 'British Indian Ocean Territory', 'IO');
insert into country (id, name, two_digit_code) values (107, 'Iraq', 'IQ');
insert into country (id, name, two_digit_code) values (108, 'Iran, Islamic Republic of', 'IR');
insert into country (id, name, two_digit_code) values (109, 'Iceland', 'IS');
insert into country (id, name, two_digit_code) values (110, 'Italy', 'IT');
insert into country (id, name, two_digit_code) values (111, 'Jersey', 'JE');
insert into country (id, name, two_digit_code) values (112, 'Jamaica', 'JM');
insert into country (id, name, two_digit_code) values (113, 'Jordan', 'JO');
insert into country (id, name, two_digit_code) values (114, 'Japan', 'JP');
insert into country (id, name, two_digit_code) values (115, 'Kenya', 'KE');
insert into country (id, name, two_digit_code) values (116, 'Kyrgyzstan', 'KG');
insert into country (id, name, two_digit_code) values (117, 'Cambodia', 'KH');
insert into country (id, name, two_digit_code) values (118, 'Kiribati', 'KI');
insert into country (id, name, two_digit_code) values (119, 'Comoros', 'KM');
insert into country (id, name, two_digit_code) values (120, 'Saint Kitts and Nevis', 'KN');
insert into country (id, name, two_digit_code) values (121, 'Korea, Democratic People''s Republic of', 'KP');
insert into country (id, name, two_digit_code) values (122, 'Korea, Republic of', 'KR');
insert into country (id, name, two_digit_code) values (123, 'Kuwait', 'KW');
insert into country (id, name, two_digit_code) values (124, 'Cayman Islands', 'KY');
insert into country (id, name, two_digit_code) values (125, 'Kazakhstan', 'KZ');
insert into country (id, name, two_digit_code) values (126, 'Lao People''s Democratic Republic', 'LA');
insert into country (id, name, two_digit_code) values (127, 'Lebanon', 'LB');
insert into country (id, name, two_digit_code) values (128, 'Saint Lucia', 'LC');
insert into country (id, name, two_digit_code) values (129, 'Liechtenstein', 'LI');
insert into country (id, name, two_digit_code) values (130, 'Sri Lanka', 'LK');
insert into country (id, name, two_digit_code) values (131, 'Liberia', 'LR');
insert into country (id, name, two_digit_code) values (132, 'Lesotho', 'LS');
insert into country (id, name, two_digit_code) values (133, 'Lithuania', 'LT');
insert into country (id, name, two_digit_code) values (134, 'Luxembourg', 'LU');
insert into country (id, name, two_digit_code) values (135, 'Latvia', 'LV');
insert into country (id, name, two_digit_code) values (136, 'Libyan Arab Jamahiriya', 'LY');
insert into country (id, name, two_digit_code) values (137, 'Morocco', 'MA');
insert into country (id, name, two_digit_code) values (138, 'Monaco', 'MC');
insert into country (id, name, two_digit_code) values (139, 'Moldova, Republic of', 'MD');
insert into country (id, name, two_digit_code) values (140, 'Montenegro', 'ME');
insert into country (id, name, two_digit_code) values (141, 'Saint Martin (French part)', 'MF');
insert into country (id, name, two_digit_code) values (142, 'Madagascar', 'MG');
insert into country (id, name, two_digit_code) values (143, 'Marshall Islands', 'MH');
insert into country (id, name, two_digit_code) values (144, 'Macedonia, the former Yugoslav Republic of', 'MK');
insert into country (id, name, two_digit_code) values (145, 'Mali', 'ML');
insert into country (id, name, two_digit_code) values (146, 'Myanmar', 'MM');
insert into country (id, name, two_digit_code) values (147, 'Mongolia', 'MN');
insert into country (id, name, two_digit_code) values (148, 'Macao', 'MO');
insert into country (id, name, two_digit_code) values (149, 'Northern Mariana Islands', 'MP');
insert into country (id, name, two_digit_code) values (150, 'Martinique', 'MQ');
insert into country (id, name, two_digit_code) values (151, 'Mauritania', 'MR');
insert into country (id, name, two_digit_code) values (152, 'Montserrat', 'MS');
insert into country (id, name, two_digit_code) values (153, 'Malta', 'MT');
insert into country (id, name, two_digit_code) values (154, 'Mauritius', 'MU');
insert into country (id, name, two_digit_code) values (155, 'Maldives', 'MV');
insert into country (id, name, two_digit_code) values (156, 'Malawi', 'MW');
insert into country (id, name, two_digit_code) values (157, 'Mexico', 'MX');
insert into country (id, name, two_digit_code) values (158, 'Malaysia', 'MY');
insert into country (id, name, two_digit_code) values (159, 'Mozambique', 'MZ');
insert into country (id, name, two_digit_code) values (160, 'Namibia', 'NA');
insert into country (id, name, two_digit_code) values (161, 'New Caledonia', 'NC');
insert into country (id, name, two_digit_code) values (162, 'Niger', 'NE');
insert into country (id, name, two_digit_code) values (163, 'Norfolk Island', 'NF');
insert into country (id, name, two_digit_code) values (164, 'Nigeria', 'NG');
insert into country (id, name, two_digit_code) values (165, 'Nicaragua', 'NI');
insert into country (id, name, two_digit_code) values (166, 'Netherlands', 'NL');
insert into country (id, name, two_digit_code) values (167, 'Norway', 'NO');
insert into country (id, name, two_digit_code) values (168, 'Nepal', 'NP');
insert into country (id, name, two_digit_code) values (169, 'Nauru', 'NR');
insert into country (id, name, two_digit_code) values (170, 'Niue', 'NU');
insert into country (id, name, two_digit_code) values (171, 'New Zealand', 'NZ');
insert into country (id, name, two_digit_code) values (172, 'Oman', 'OM');
insert into country (id, name, two_digit_code) values (173, 'Panama', 'PA');
insert into country (id, name, two_digit_code) values (174, 'Peru', 'PE');
insert into country (id, name, two_digit_code) values (175, 'French Polynesia', 'PF');
insert into country (id, name, two_digit_code) values (176, 'Papua New Guinea', 'PG');
insert into country (id, name, two_digit_code) values (177, 'Philippines', 'PH');
insert into country (id, name, two_digit_code) values (178, 'Pakistan', 'PK');
insert into country (id, name, two_digit_code) values (179, 'Poland', 'PL');
insert into country (id, name, two_digit_code) values (180, 'Saint Pierre and Miquelon', 'PM');
insert into country (id, name, two_digit_code) values (181, 'Pitcairn', 'PN');
insert into country (id, name, two_digit_code) values (182, 'Puerto Rico', 'PR');
insert into country (id, name, two_digit_code) values (183, 'Palestinian Territory, Occupied', 'PS');
insert into country (id, name, two_digit_code) values (184, 'Portugal', 'PT');
insert into country (id, name, two_digit_code) values (185, 'Palau', 'PW');
insert into country (id, name, two_digit_code) values (186, 'Paraguay', 'PY');
insert into country (id, name, two_digit_code) values (187, 'Qatar', 'QA');
insert into country (id, name, two_digit_code) values (188, 'Réunion', 'RE');
insert into country (id, name, two_digit_code) values (189, 'Romania', 'RO');
insert into country (id, name, two_digit_code) values (190, 'Serbia', 'RS');
insert into country (id, name, two_digit_code) values (191, 'Russian Federation', 'RU');
insert into country (id, name, two_digit_code) values (192, 'Rwanda', 'RW');
insert into country (id, name, two_digit_code) values (193, 'Saudi Arabia', 'SA');
insert into country (id, name, two_digit_code) values (194, 'Solomon Islands', 'SB');
insert into country (id, name, two_digit_code) values (195, 'Seychelles', 'SC');
insert into country (id, name, two_digit_code) values (196, 'Sudan', 'SD');
insert into country (id, name, two_digit_code) values (197, 'Sweden', 'SE');
insert into country (id, name, two_digit_code) values (198, 'Singapore', 'SG');
insert into country (id, name, two_digit_code) values (199, 'Saint Helena', 'SH');
insert into country (id, name, two_digit_code) values (200, 'Slovenia', 'SI');
insert into country (id, name, two_digit_code) values (201, 'Svalbard and Jan Mayen', 'SJ');
insert into country (id, name, two_digit_code) values (202, 'Slovakia', 'SK');
insert into country (id, name, two_digit_code) values (203, 'Sierra Leone', 'SL');
insert into country (id, name, two_digit_code) values (204, 'San Marino', 'SM');
insert into country (id, name, two_digit_code) values (205, 'Senegal', 'SN');
insert into country (id, name, two_digit_code) values (206, 'Somalia', 'SO');
insert into country (id, name, two_digit_code) values (207, 'Suriname', 'SR');
insert into country (id, name, two_digit_code) values (208, 'Sao Tome and Principe', 'ST');
insert into country (id, name, two_digit_code) values (209, 'El Salvador', 'SV');
insert into country (id, name, two_digit_code) values (210, 'Syrian Arab Republic', 'SY');
insert into country (id, name, two_digit_code) values (211, 'Swaziland', 'SZ');
insert into country (id, name, two_digit_code) values (212, 'Turks and Caicos Islands', 'TC');
insert into country (id, name, two_digit_code) values (213, 'Chad', 'TD');
insert into country (id, name, two_digit_code) values (214, 'French Southern Territories', 'TF');
insert into country (id, name, two_digit_code) values (215, 'Togo', 'TG');
insert into country (id, name, two_digit_code) values (216, 'Thailand', 'TH');
insert into country (id, name, two_digit_code) values (217, 'Tajikistan', 'TJ');
insert into country (id, name, two_digit_code) values (218, 'Tokelau', 'TK');
insert into country (id, name, two_digit_code) values (219, 'Timor-Leste', 'TL');
insert into country (id, name, two_digit_code) values (220, 'Turkmenistan', 'TM');
insert into country (id, name, two_digit_code) values (221, 'Tunisia', 'TN');
insert into country (id, name, two_digit_code) values (222, 'Tonga', 'TO');
insert into country (id, name, two_digit_code) values (223, 'Turkey', 'TR');
insert into country (id, name, two_digit_code) values (224, 'Trinidad and Tobago', 'TT');
insert into country (id, name, two_digit_code) values (225, 'Tuvalu', 'TV');
insert into country (id, name, two_digit_code) values (226, 'Taiwan, Province of China', 'TW');
insert into country (id, name, two_digit_code) values (227, 'Tanzania, United Republic of', 'TZ');
insert into country (id, name, two_digit_code) values (228, 'Ukraine', 'UA');
insert into country (id, name, two_digit_code) values (229, 'Uganda', 'UG');
insert into country (id, name, two_digit_code) values (230, 'United States Minor Outlying Islands', 'UM');
insert into country (id, name, two_digit_code) values (231, 'Uruguay', 'UY');
insert into country (id, name, two_digit_code) values (232, 'Uzbekistan', 'UZ');
insert into country (id, name, two_digit_code) values (233, 'Holy See (Vatican City State)', 'VA');
insert into country (id, name, two_digit_code) values (234, 'Saint Vincent and the Grenadines', 'VC');
insert into country (id, name, two_digit_code) values (235, 'Venezuela', 'VE');
insert into country (id, name, two_digit_code) values (236, 'Virgin Islands, British', 'VG');
insert into country (id, name, two_digit_code) values (237, 'Virgin Islands, U.S.', 'VI');
insert into country (id, name, two_digit_code) values (238, 'Viet Nam', 'VN');
insert into country (id, name, two_digit_code) values (239, 'Vanuatu', 'VU');
insert into country (id, name, two_digit_code) values (240, 'Wallis and Futuna', 'WF');
insert into country (id, name, two_digit_code) values (241, 'Samoa', 'WS');
insert into country (id, name, two_digit_code) values (242, 'Yemen', 'YE');
insert into country (id, name, two_digit_code) values (243, 'Mayotte', 'YT');
insert into country (id, name, two_digit_code) values (244, 'South Africa', 'ZA');
insert into country (id, name, two_digit_code) values (245, 'Zambia', 'ZM');
insert into country (id, name, two_digit_code) values (246, 'Zimbabwe', 'ZW');
